server:
  port: 8083
spring:
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
      timeout: 5000
    password: ''
    port: 6379
  servlet:
    multipart:
      max-file-size: 17MB
      max-request-size: 70MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.41.29.154:3306/pet_platform?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
mybatis-plus:
  global-config:
    db-config:
      table-prefix: pet_
#      使用数据库的自增方法
      id-type: auto
#      mybatis-plus的日志
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
files:
  upload:
    path: D:/pictures/files/
mybatis:
  configuration:
    map-underscore-to-camel-case: true

alipay:
  appId: 2021000122608480
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6x6FdjdwGb/TuRxIy8eAvvLDT6j0I5VUKk7nY4/nCZuYPanmKD9SOP5ZeyWYMdXOYPvpCxfPt0dLvWzlJqIlOF2ZZQjF92Z93Xa+gqLiMq577h9irMcCgiSoKdOf5NkVjRoIpXGyolDimTLYj70sTIuv/Eal3SEMVuFvA63cQnfnwuB7EybLCX7U5FNqHBnDss9CiaVg4clXzqumq8uvtWahHA7bWcSuw0Qt6SxtLzJNqfzhDjVJbAFb8MQ7Sc8BHL4+2EzQxwGYDB3SEalDUQDrM918bHDKJE4/PP29+tUXQDYaR5sPnM42Zv6D5s+s+wn9KMOh+sjwMiaYHqq2nAgMBAAECggEBAKpN08hlzLTh6EZK70EcYfmk5uaSscwmrv/R6qbkV5r2D9cGkoNcI8cAG6+Zmz7I6PlskuvHar7xjo9IclfDIE7f7yZ7wHyrrUc9WSH4NS2uXmuiVeDioGzAJGEcb1dAMMxwQcZMy5Z6b5zSXVEuoxlzwhL0m7xzWxe23ZJuIEY49RHijF5lU6DP0VOH3R+EvPS94smgTV+929BtCFU0LBbe2zRDTUgQuDFv/5VGLnKRI3Y5jLVFPNC4a07pcyndnSg6ax/FkgD6H895zpUKDk7igTiMrPR5gG4J+RCjgKfla4xnW1g43PK4QtcoTSN14yiDezVat+TG74vfSx5XuUECgYEA61E9InDoSLCfQvZDSp+Q759p5vqRz5JtLiHa3CAAUSrJKF8iThVQIGk7ElUwMhLt5eG/b9xDGRF2eYjcIqwq8fFgaGW2DrEIdruSdUyXjtokLTRGAKLcxNvDqj+Ybbac2b+eMbwweDNC8yprtUnK8uK5qTldAktlhEEOdUA328kCgYEAyzJFpc1aVkAkaSFP2rCY+a2viIdjuwd6VfmiS6trPSpUYFyNG93FwfGlbQP5FcYBsiWGe8HzNqyU1QoYGL3ENYW9zBZ1BudL0Wu16vNgwJogGMphUZQITAGLS5ALSIpK9alLvYFmfJg+CSfFI6fPCBj3+aeEPn0yV/2Xxz8VFe8CgYB27Y36NBoRcsJq8087Db4QfP7m78h1oclwQUf9bGb8nqUftEUANaFTYBusvkUnaY22WwuHm0iGCN9ZuSOYmm7x7E4PNSh38F0YtN/mTJlkZzdVaU/fzm/JRlBzYMTG3j4ThtaKyFOuzCmP/+aDrxHVA2VV81ngaP6bgs2t0JDqkQKBgDtBpd38TOPqQLQH6umzpmjppc8C7KqWO67m5dV7YAKuXXzcgKonuowclEl+Zx1aaRQyrU1Z+jtviNe34d8VOCsDnZ3uzqH8wbeI2bxyzTxdtg6Etmy75s+Dg8O9dgzph4KspFHXcrPTEgRJfMwxG8cYwPglSgOPLydJ5QFN/DAxAoGBAKDqQbiw69lahCD79WjNIHzg1KOT3s6OH9rPnqenZva5ySBlkhbXEUw/51jMLzAbo8GFdikOv3WdBhFv4Gn+NqqXi1S48RxVoow1drIM4/h5vNZe3iH4cQex9PLiYza8OiyAk/buu5AsO6YVD2HhlTszYfh2zucAJnhr9jlqEUb7
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhsiL8e+HUqOr8q7vj/o8Gh8II0sq/TjCcCurgRMB0pU2X8gqNJR3fHs67kZqUF0hVEm7qSYXnWPDlq2c0NnicJh1fYASn4vvI2nE7FKlt5x4i8K8kJK24lDuWsLmQfB+Ycs5zUlArWlCnzMEzRmlioMQEOMyuu/2D7hbEG+mQIenXQ9q5baf7YMxOr1eO9gU6T0LEJB9Tq/EJ+Otxyj5PKIpvSx4KgggiNtuIK3mjV19vWQDywnyydXkxOmrtsCFxmWDqvgWIQnmCeMDJUXIQ0zLgKUisogKI9n0YrvT/JphU4OP2BbEmnBIEuO7ywuj5G18vPu2gfJGwEfc2tU54wIDAQAB
  notify-url: http://121.41.29.154:8083/alipay/notify
#百度内容审核
baidu:
  examine:
    #你的 App ID
    AppID: 30762463
    #你的 Api Key
    API_Key: 26VoAGTMdxOdkdrXnKAgrCn7
    #你的 Secret Key
    Secret_Key: 5kcf5IR6QKUm6mkssfOaUZchmZjXQiuf
#七牛云
qiniu:
  accessKey: 'BYsk2nsmOjkAVdtJcaZiHDTJaKHuwWuu7h4r-vnp'
  accessSecretKey: 'DOQHft2ZnLI8gtrAipMVPDQheIG8Ln9sJu4rFaz8'

